# Generated by Django 3.2.3 on 2021-05-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_cal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='end_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
    ]
